version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

  api-gateway:
    image: movieserver/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  auth-service:
    image: movieserver/auth-service
    depends_on:
      - rabbitmq
      - database-service
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  database-service:
    image: movieserver/database-service
    volumes:
      - db_data:/app/data
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  llm-service:
    image: movieserver/llm-service
    depends_on:
      - rabbitmq
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  telegram-service:
    image: movieserver/telegram-service
    depends_on:
      - rabbitmq
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

networks:
  frontend:
  backend:

volumes:
  rabbitmq_data:
  db_data: